server:
  port: 9092

spring:
  application:
    name: USER-MS
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: sys as sysdba
    password: manager01
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
